import type { Metadata } from "next";
import { Oswald, Inter, Sofia_Sans_Extra_Condensed } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const oswald = Oswald({
  variable: "--oswald",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

const inter = Inter({
  variable: "--inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "800", "900"],
});

const sofia = Sofia_Sans_Extra_Condensed({
  variable: "--sofia",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "800", "900"],
});

const SuisseIntlMedium = localFont({
  src: "../../public/fonts/SuisseIntl-Medium.ttf",
  variable: "--SuisseIntlMedium",
  display: "swap",
});

const SuisseRegular = localFont({
  src: "../../public/fonts/SuisseRegular.ttf",
  variable: "--SuisseRegular",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${oswald.variable} ${inter.variable} ${sofia.variable} ${SuisseIntlMedium.variable} ${SuisseRegular.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
